# Generated by Django 5.0.4 on 2024-04-24 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_order_customer_mobile_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='menu_items',
        ),
        migrations.RemoveField(
            model_name='ordereditem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='customer_mobile_number',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='customer_user_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_mobile_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_user_name',
        ),
        migrations.AddField(
            model_name='cart',
            name='order_id',
            field=models.CharField(default=0, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='clerk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.clerk'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.order')),
            ],
        ),
        migrations.DeleteModel(
            name='Contains',
        ),
        migrations.DeleteModel(
            name='OrderedItem',
        ),
    ]
