# Generated by Django 5.0.4 on 2024-04-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_cart_menu_items_remove_ordereditem_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(choices=[(0, 'Pending'), (1, 'Confirmed')], default=1),
        ),
    ]
