# Generated by Django 5.0.4 on 2024-04-24 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
